### ISSUE TITLE
Can not find the YouTube OPML export button

### ISSUE THREAD

**Issue by AboutRSS** [theborg3of5/Userscripts#1]
Thanks for the creation but I can not find the YouTube OPML export button after following procedures in "how to use". The browser is Chrome 64 bit V87.0.4280.88 and the js was installed via tampermonkey v4.11.

**Comment by theborg3of5** [comment]
The button should appear in the sidebar, next to the "Subscriptions" header:

![image](https://user-images.githubusercontent.com/2433038/103042723-31c2b700-4540-11eb-9c12-89adb6f91feb.png)

Note that it will only appear when the "Subscriptions" header is visible in the sidebar, such as on the home page. What page are you trying to access it from?

**Comment by AboutRSS** [comment]
Got it. It works. I did not find the button because I did not switch language to Eng. Thanks.

I'll mention your Userscripts in my Telegram Channel t.me/aboutrss in the near future.

**Comment by RocksteadyTC** [comment]
I dont see this button anywhere. English, Firefox, Linux.

![image](https://user-images.githubusercontent.com/34389545/105878007-31499000-5fc6-11eb-94cc-c6e34a4412cc.png)

**Comment by theborg3of5** [comment]
Unfortunately I don't have a way to test on Linux - I'd recommend poking around in the page structure to see what's going wrong. Code-wise, the problem is likely in the "Find the subscriptions section label" section - we basically look through all of the <yt-formatted-string> elements with id="guide-section-title" until we find one that reads "Subscriptions". I'm guessing YouTube serves up a slightly different structure in Linux + Firefox.

Please feel free to submit a pull request if you figure out a good way to identify the right label on your setup - I'd be happy to add it in.
